### ISSUE TITLE
paredit-mode causes strange square bracket behaviour

### ISSUE THREAD

**Issue by mrmagooey** [extemporelang/extempore-emacs-mode#2]
With paredit-mode on, inserting a `[` causes an extra space to be inserted and the error `up-list: Scan error: "Unbalanced parentheses", 1107, 1` to be printed (where some of the integers are cursor positions).

My guess is that its related to the syntax table.

**Comment by benswift** [comment]
There have been some syntax table fixes over the last little while---maybe this is now fixed?
