### ISSUE TITLE
Reconnect buffers automatically when process is restarted

### ISSUE THREAD

**Issue by mrmagooey** [extemporelang/extempore-emacs-mode#3]
Currently if the emacs buffer loses connection to the extempore process, it abandons all hope and decides that extempore process is gone for good, forcing the user to manually reconnect to any new processes.

Given that restarting extempore processes is a fairly common action, I think it would be preferable if once the connection was lost, extempore-mode would attempt to keep using the previous connection information if asked to send code. 

What this reconnection attempt heuristic looks like I'm not sure, some suggestions are:
- Keep trying forever, reporting any failure, until the user manually calls `extempore-disconnect`.
- Only try for a particular time period and if no successful connection is made within that time period only then report disconnection.

**Comment by benswift** [comment]
This is a nice idea in some ways, but the recent change to not require host:port every time hopefully negates the need somewhat. So let's close it for now.
